version: '3.1'
services:
  identidock:
    build: .
    ports:
    - "5000:5000"
    environment:
      ENV: DEV
    volumes:
    - ./app:/app
  dnmonster:
    image: amouat/dnmonster
  redis:
    image: redis